import 'package:flutter/material.dart';

const Color SLIDER_ACTIVE_TRACK_COLOR = Color(0xFF1BB3A8);
const Color SLIDER_INACTIVE_TRACK_COLOR = Color(0xFFEAF1F7);
const MaterialColor SLIDER_THUMB_COLOR = Colors.green;

const PERCENT_BUTTON_TEXT_COLOR_SELECTED = Colors.white;
const PERCENT_BUTTON_BACKGROUND_COLOR_SELECTED = Color(0xFF25D9A5);
const PERCENT_BUTTON_TEXT_COLOR_UNSELECTED = Color(0xFF25D9A5);
const PERCENT_BUTTON_BACKGROUND_COLOR_UNSELECTED = Colors.transparent;
const PERCENT_BUTTON_BORDER_COLOR = Color(0xFF25D9A5);

const TEXT_HEADER_COLOR = Color(0xFF939BA0);

const TIP_INPUT_CURSOR_COLOR = Color(0xFF939BA0);
const TIP_INPUT_COLOR = Color(0xFF939BA0);
const TIP_INPUT_FILL_COLOR = Color(0xFFECF4FA);
const TIP_INPUT_LABEL_COLOR = Color(0xFF939BA0);

const TIP_DISPLAY_BACKGROUND_COLORS = [
  const Color(0xFF20D5A6),
  const Color(0xFF1DB9AB),
  const Color(0xFF19A3AE)
];

const TIP_SUB_TEXT_COLOR = Colors.white;

const TRANSPARENT_ROUND_SLIDER_COLOR = Color(0xFF25D9A5);